# Generated by Django 4.0.4 on 2022-04-29 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('itemname', models.CharField(db_column='itemName', max_length=20)),
                ('amount', models.IntegerField()),
                ('subtotal', models.DecimalField(decimal_places=4, max_digits=19)),
                ('total', models.DecimalField(decimal_places=4, max_digits=19)),
                ('itemid', models.CharField(db_column='itemId', max_length=10)),
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Currentorders',
            fields=[
                ('ordernumber', models.IntegerField(db_column='OrderNumber')),
                ('items', models.CharField(max_length=20)),
                ('total', models.DecimalField(decimal_places=4, max_digits=19)),
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('progress', models.CharField(db_column='Progress', max_length=20)),
                ('quantity', models.IntegerField(db_column='Quantity')),
            ],
        ),
        migrations.CreateModel(
            name='Discountcodes',
            fields=[
                ('discountcode', models.CharField(db_column='DiscountCode', max_length=10, primary_key=True, serialize=False)),
                ('discountpercentage', models.IntegerField(db_column='DiscountPercentage')),
                ('newtotal', models.DecimalField(db_column='newTotal', decimal_places=4, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='Userlogins',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('phonenumber', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(db_column='itemName', max_length=30)),
                ('itemid', models.CharField(db_column='itemID', max_length=30)),
                ('itemprice', models.DecimalField(db_column='itemPrice', decimal_places=4, max_digits=19)),
                ('quantity', models.IntegerField(db_column='Quantity')),
                ('itemimage', models.ImageField(db_column='itemImage', upload_to='')),
                ('itemcategory', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pages.category')),
            ],
        ),
    ]
