# Generated by Django 4.0.3 on 2022-05-02 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Discountcodes',
            fields=[
                ('discountcode', models.CharField(db_column='DiscountCode', max_length=10, primary_key=True, serialize=False)),
                ('discountpercentage', models.IntegerField(db_column='DiscountPercentage')),
                ('newtotal', models.DecimalField(db_column='newTotal', decimal_places=4, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(db_column='itemName', max_length=30)),
                ('itemid', models.CharField(db_column='itemID', max_length=30)),
                ('itemprice', models.DecimalField(db_column='itemPrice', decimal_places=4, max_digits=19)),
                ('quantity', models.IntegerField(db_column='Quantity')),
                ('itemimage', models.ImageField(blank=True, null=True, upload_to='')),
                ('itemcategory', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pages.category')),
            ],
        ),
        migrations.CreateModel(
            name='Currentorders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernumber', models.IntegerField(db_column='OrderNumber')),
                ('total', models.DecimalField(decimal_places=4, max_digits=19)),
                ('progress', models.CharField(db_column='Progress', max_length=20)),
                ('quantity', models.IntegerField(db_column='Quantity')),
                ('complete', models.BooleanField(default=False, null=True)),
                ('items', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.items')),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('itemname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.items')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.currentorders')),
            ],
        ),
    ]
